### ISSUE TITLE
Chem | Top menu Sketcher and Property Pane Sketcher: don't work on 2 molecular columns

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1326]
Platform: public "Version":"1.10.2"
Data: [smiles_2_columns](https://public.datagrok.ai/f/System.AppData/Chem/tests/smiles_2_columns.csv)

To reproduce for Top Menu Sketcher:

1. Go to Chem > Sketcher.
2. Draw cyclohexane. 
Actual: empty dataframe
Expected: filtered data

To reproduce for Property Pane Sketcher:

1. Click the molecule Column
2. Go to Property Pane > Filter.
2. Draw cyclohexane. 
Actual: empty dataframe
Expected: filtered data

![Image](https://user-images.githubusercontent.com/111368431/206709139-7f20dbec-4240-4ef7-af5a-512657d4bbc2.gif)

**Comment by MariaDolotova** [comment]
@ahadzhanian , as for property panel - the dataset is empty after entering cyclohexane since smiles1 column doesn't containg molecules with cyclohexane substructure. So the result is correct. If you choose benzene for example, you will see the filtered rows.
As for top-menu Sketcher - it indeed doesn't filter. And this issue is duplicate of #1324

**Comment by ahadzhanian** [comment]
I've checked and closed the issue as duplicated
