### ISSUE TITLE
Chem: add a property to package settings to select the default sketcher

### ISSUE THREAD

**Issue by onuf** [datagrok-ai/public#1370]
The use case: set Sketcher to Marvin by default to all app users (so that the users won’t have to switch on the first use manually).
Sketcher > Marvin, other sketchers...

**Comment by dnillovna** [comment]
@MariaDolotova, what do you think of changing the list a bit?

Instead of 
- openChemLibSketcher
- ketcherSketcher
- marvinSketcher
- chemDrawSketcher

![Image](https://user-images.githubusercontent.com/86597056/209343098-15894959-ffba-4487-8ad2-5ce917635168.png)

Make a capitalized list of choices:
- OpenChemLib
- Ketcher
- Marvin
- ChemDraw
