### ISSUE TITLE
Improve usability of range filters

### ISSUE THREAD

**Issue by DanTkachev** [datagrok-ai/public#1465]
**Acceptance criteria**
- Row with range input fields is always displayed. Remove possibility to collapse this row (= remove keyboard icon)
- Tooltips showing the current range values are removed (as the same values are shown in range input fields)
- The Reset icon is added to the action bar (currently, once the range has been changed, it's not possible to easily get back to all values in the range filter again)
- The range filter is treated as a checkbox filter, where the part with the distribution is the first checkbox and the missing value filter becomes the second checkbox
<img width="336" alt="Range filter" src="https://user-images.githubusercontent.com/114074888/211579613-c1c3df55-e2ec-4834-8cdf-df3f1a7ff53e.png">

**Comment by skalkin** [comment]
```
    Reset
----------------
[x] Histogram
[x] Slider
[ ] Min / max
    Missing values >
	   [*] Keep missing values
	   [ ] Filter out missing values
	   [ ] Show only missing values    // remove everything and show "Only missing values"
```

**Comment by AnnaMuza** [comment]
@dionissqq please add support for layouts/projects and see how the Reset button behaves when "Show only missing values" is selected (filter state is not updated)

![Image](https://user-images.githubusercontent.com/70022930/212964864-02981bfc-6d31-4032-9706-cd4c8cc4cb43.gif)

**Comment by onuf** [comment]
Comes with the `v1.13.0` update.
@dionissqq please see the comment above and close the ticket once everything's fixed.

**Comment by onuf** [comment]
A few things to improve:

- [ ] apply property updates at once (Filters > Misc > Show Histogram / Min Max / Search Box)
- [ ] save the configuration to the layout (also, if a single numeric filter is customized differently than the rest of filters, this should be saved to layout as well overriding the look defined in properties)

**Comment by katerina-stepanova** [comment]
v1.13.2
Issues discovered:
1. Values in the input fields do not match actual range after saving and re-applying layout:
- Open table
- Add numerical filter, show min/max, set up some filtering range
- Save layout
- Close and re-open table
- Re-apply layout
**Expected:** values shown match actually set range.
**Actual:** min/max values existing in the table are shown instead of actually set range:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/15780643/220877990-cab25d6c-8fac-4351-a0be-bb877e730877.png">


2. Filter state is not updated on reset if 'show only missing values' is selected:
![2023-02-23_12-31-52 (1)](https://user-images.githubusercontent.com/15780643/220878068-4bfbcd09-3470-416d-801a-faa6be460bd8.gif)

**Comment by ahadzhanian** [comment]
DG 1.14.1
