### ISSUE TITLE
Viewers: Inconsistencies in saved layouts won't allow creating a viewer when such layout is applied

### ISSUE THREAD

**Issue by onuf** [datagrok-ai/public#2011]
Example of inconsistencies: negative width value.
Refactor code to create a viewer despite such errors. Add warnings for users if a layout has invalid values/properties.

**Comment by ahadzhanian** [comment]
DG 1.15.3

**Comment by katerina-stepanova** [comment]
DG 1.15.3

There are no negative values on saving layout, but issue with hidden viewer after switching between screens with different resolutions can be still reproduced.

@JianmeiFan used Dell monitor display resolution: 2560X1440 to check. It still does not work as expected. One of viewer is hidden from other viewers although the layout doesn't have negative width value any more.

**Comment by katerina-stepanova** [comment]
DG 1.15.4
I was able to reproduce the issue in native DG.

**Steps:**
1. Set low screen resolution, e.g. 1024x640
2. Open some table
3. Open filters
4. Add multiple scatter plots, so that there are at least 6 scatter plots in the bottom row
5. Set up each scatter plot so that colour legend is displayed
<img width="1023" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/36998c51-a56c-438a-8f83-1928c20d8e33">
6. Save layout
7. Close browser tab
8. Switch screen resolution to a higher one, e.g. 1680x1050
9. Open datagrok again, open the same table
10. Apply previously saved layout

**Actual results:** some scatter plots are hidden:
<img width="1634" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/e7e5e41a-c4a8-406a-bfec-830f58fe732a">

**Comment by ahadzhanian** [comment]
DG 1.16.0

**Comment by ahadzhanian** [comment]
Reopened due to the fixes in #2328

**Comment by ahadzhanian** [comment]
DG 1.17.0
