### ISSUE TITLE
#2129: Network diagram: auto layout

### ISSUE THREAD

**Issue by dionissqq** [datagrok-ai/public#2129]

**Comment by ahadzhanian** [comment]
There are some comments:

- Not the entire diagram fits in the viewer
- Increasing the viewer's size does not increase informativeness (node size increases)

![Image](https://github.com/datagrok-ai/public/assets/111368431/6ffbcbca-ce1c-41ca-8ce9-665ca826fede)

**Comment by LaykDimon** [comment]
not sure about the diagram fitting in the viewer, as we can simply reset it by double clicking
don't know if it's expected behavior because we save it in the same state it was while shrinking the root window

about the node size increasing - what do you mean?
do you mean that we don't need to increase node size or what?

**Comment by ahadzhanian** [comment]
1. The idea is to make the viewer as informative as possible, so we should strive to fit the diagram into the viewer as much as possible - to make everything visible to the greatest extent possible.
2. Increasing the size of nodes makes sense up to a certain point. It's better to try to fit the entire diagram into the viewer.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14607

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16130
