### ISSUE TITLE
Meta tags/information in function description

### ISSUE THREAD

**Issue by denyzhirkov** [datagrok-ai/public#2319]
Suddenly found that meta information in function description doesnt work correctly (not working at all).
Need **meta.role: converter**, **meta.inputRegexp**

```
//name: searchSmiles
//meta.role: converter
//meta.inputRegexp: (\d)
//input: string id = "abcd"
//output: string smiles { semType: Molecule }
export async function searchSmiles(id: string) {
  // test response
  // return id;
  return 'COc2ccc(CC(C)(C)NCC(O)COc1cccc(c1)OC)cc2';
}
```

**Comment by MariaDolotova** [comment]
Dear @denyzhirkov , can you please confirm if the Chembl package is installed on your environment (the reason that function is not working may be in one of Chembl's scripts with quite an agressive regexp. It may be called instead of your custom function. Anyway this issue has been fixed already and fix will be in Datagrok version 1.17.0).
I have tried the fuction above with the applicable regexp on an environment without Chembl package and it worked.
![nx_regexp](https://github.com/datagrok-ai/public/assets/44060410/e44839a3-888c-4f69-adec-24a6ae9c2262)

**Comment by denyzhirkov** [comment]
@MariaDolotova Hey!
No, Chembl is not installed on my env. Will try your fix on 1.17.0.
Thank you!

**Comment by MariaDolotova** [comment]
@denyzhirkov , if Chembl package is not there then the fix from 1.17.0 seems to not be related to your issue... Could you please provide a regexp you are using in your function? And also do you get any errors in console when trying to run it?

**Comment by denyzhirkov** [comment]
No errors, and the example is in description of the issue. The function just ignored the regexp from the meta and pass the input arg inside.

**Comment by denyzhirkov** [comment]
We can close this issue. Thx @MariaDolotova for online help with this problem.
