### ISSUE TITLE
Line chart: Optimize the display of labels on the x-axis

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#2388]
Starting from a certain number of data points on the x-axis, some of the labels stop being displayed. Space is underutilized (at some point, half or even two-thirds of the labels on the axis disappear, even though there is more than enough space to render them)

![Linechart_Xlabels_visibility](https://github.com/datagrok-ai/public/assets/111368431/2d479eb7-c7dc-4b72-8a4e-cecd3077054d)

**Comment by katerina-stepanova** [comment]
DG 1.16.6
There is a data-specific case when X axis labels are completely missing on the right side of the plot.

**Steps to reproduce:** 
1. Open the table from attached file:
[PubChem_compound_text_covid-19.csv](https://github.com/datagrok-ai/public/files/12818189/PubChem_compound_text_covid-19.csv)
2. Configure line chart: 'inchi' as X axis, 'heavycnt' as Y axis, split by 'depcatg'
3. Filter the table by 'depcatg' so that only the largest category is shown (630 rows)
4. See the line chart

Same issue can be reproduced when row source = selected, and the same category from 'depcatg' column is selected.

**Expected results:** right side of the line chart should also have some X axis labels, as there is some data displayed.

**Actual results:** no X axis labels in the right side of the line chart:
![image](https://github.com/datagrok-ai/public/assets/15780643/15318af2-0b6b-4362-ad4f-8bb65d1fd6d0)

**Comment by katerina-stepanova** [comment]
DG 1.16.6
(Data-specific) Labels on the X axis do not correspond to any of the dots on the line chart in some cases.

**Steps to reproduce:**
1. Open the table from the attached file:
[PubChemReduced.csv](https://github.com/datagrok-ai/public/files/12820244/PubChemReduced.csv)
3. Configure line chart as in the comment above
4. Zoom in line chart

**Expected results:** Labels on the X axis should be directly below the dots.
**Actual results:** Some labels on the X axis do not correspond to any of the dots:
<img width="607" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/f72ba85e-1c5c-472d-a9aa-c89716885fe2">

_Note: this reduced file can be also used to reproduce the issue from the comment above_

**Comment by ahadzhanian** [comment]
DG 1.17.0
