### ISSUE TITLE
Scaffold tree: colour is not inherited by child node properly

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2474]
chem 1.8.3

**Steps to reproduce:**
1. Open a table, e.g. SPGI
2. Add scaffold tree
3. Draw at least two nodes: parent and a child
4. Enable colouring for the parent > both parent and child node have the same colour set:
<img width="332" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/4014dc3a-a284-4bb7-a02d-5d006f4a5368">

5. Select checkbox for the child node to filter table by this item
6. See the structures highlighting

**Expected results:** structures should be highlighted by parent node's colour that was inherited by the child.
**Actual results:** default highlighting colour is used to highlight structures matching the child node:
<img width="978" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/a2d21ebb-e578-47f8-998d-d2881a42c4f3">
Issue can be also reproduced for scaffold tree filter in filter panel.

**Comment by Aleksashka11** [comment]
This is our expected behaviour.
If the structure has a parent color, only a part of it is highlighted. During filtering, we need the structure we are filtering by to be fully highlighted. Therefore, the part to which the parent color is attached is highlighted by it, and the remaining part is highlighted with the filter color as usual. 
If we won't provide an additional coloring for remaining part, it will be hard for user to understand by which part he is filtering.

**Comment by ahadzhanian** [comment]
![2274](https://github.com/datagrok-ai/public/assets/111368431/8ed4fedb-8d93-4029-9e7a-3b3f34e398ef)

**Comment by ahadzhanian** [comment]
Chem 1.8.4
