### ISSUE TITLE
#2841: Layout Gallery - Improved Matching

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#2841]
The layout gallery should provide a convenient way to save and restore table/viewer layouts but I have never successfully used it. It seems to never detect that I am viewing the exact same dataframe. Could the rules that match layouts be loosened? 

I always have to download the layout (table.layout file) and from one Project - then drag and drop the layout onto another browser window with another Project.

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-15607

**Comment by skalkin** [comment]
Hi @tcarolan , most likely your layout only contains a grid, and yes in that case the matching does not work as most users expect. This is how it currently works (I'll leave aside semantic types matching for the sake of simplicity):
1. When saving the layout, the "columns of interest" (name + type) that are used as data columns are collected from all viewers in a view.
2. When finding applicable layouts for the table, we look for the "columns of interest" to be a subset of this table's columns.

Now, the tricky part is the grid, since by default is shows all columns. If we were to include all of them as "columns of interest", then we would have a problem for cases when we have many columns present, but are only interested for example in a scatter plot and a histogram set up for 3 specific columns. 

But clearly, we also want to be able to easily find our layout when all we have is a grid. So we have changed the heuristics. Now we determine "columns of interest" in the following way:
1. Start with an empty set of columns
2. For all non-grid viewers, add "columns of interest" as we did previously
3. If no "columns of interest" were found previously, add visible columns from all grids.

I feel like this should satisfy most use cases. You are welcome to try it out on dev.datagrok.ai (I think you have a login) starting Friday morning :)
