### ISSUE TITLE
#2903: Core | Calculated columns : fix restoring on data refresh

### ISSUE THREAD

**Issue by LesiaPavlenko** [datagrok-ai/public#2903]
Calculated columns using MPO columns in formula are not restored on data refresh

**Comment by gasserandreas** [comment]
**Problem**
To further specify this ticket: The root cause for this issue was introduced by us having multiple sources for calculated columns. Because of that during loading sequence our module is trying to restore calculated columns in the wrong dependency order. This leads to the situation of missing columns in the resulting DataFrame.

We know Datagrok has a built in feature to solve the dependency issue for calculated columns which works excellent for all cases. To ensure we are handling the dependency issue in a consistent way, we would like to re-use your dependency solving algorithm through Datagrok JavaScript API.

**Therefore our ask would be:** can you expose your calculated columns (re)-order algorithm through native Datagrok API?

**Desired specs:**
- exposed method in `grok` JS module
- passed variables: unsorted array of calculated columns
- - type def: Array<{columnName: string, formula: string}>
- return value: sorted array with resolved dependency order of calculated columns:
- - type def: Array<{columnName: string, formula: string}>

**Comment by skalkin** [comment]
@LaykDimon should be doable?

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16198
