### ISSUE TITLE
Can not choose any column directly on the default Bar chart Value axis when aggr type is COUNT

### ISSUE THREAD

**Issue by JianmeiFan** [datagrok-ai/public#463]
**Steps to reproduce:** 
Open a Bar chart and try to adjust value axis to a desired column 
**Expected results:** 
User can choose any value column on the value axis no matter which aggregation type they have
**Actual results:** 
The default value axis only shows **count**. User can not choose any value column unless they switch **count** to other aggregation like avg etc. Or they need to use properties menu. 
![image](https://user-images.githubusercontent.com/100243033/162056544-d4e63c54-1a28-4362-a565-ce3753535c68.png)

**Comment by onuf** [comment]
@skalkin @JianmeiFan 
This behavior of the 'Value' column selector appears to be intentional. If I recall correctly, there was a discussion a while ago regarding the case of 'count' aggregation. It wasn't clear back then that the 'Value' column doesn't contribute to the calculations (as `count` means we are only looking at the Y-axis column and counting the number of values in each category). The ticket created as an outcome of this discussion stated that the column combobox on the X axis should be empty specifically when the aggregation is `count` ([GROK-8355](https://reddata.atlassian.net/browse/GROK-8355)) to prevent users from assuming that the values from the numeric column on the X axis are accounted for and displayed in the chart. 
Perhaps we should address this problem differently if the existing solution hinders the use of the value selector?

**Comment by JianmeiFan** [comment]
@onuf Thank you for your detail explaining. Yes I can understand the logic and the reason why value is not there. But UI is not intuitive and user friendly. The issue was raised by one of our users. He has hard time to find the value column. If you have a way to accommodate both of these requirements, that will be great :).
