### ISSUE TITLE
Changing the behavior of ESC button in the filter panel

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#644]
@skalkin  - we found a good idea the option you proposed last week. 

I mean changing the behavior of ESC button in the filter panel. After hitting it, instead of resetting all filters, they should just get disabled (turned off).

**Comment by katerina-stepanova** [comment]
Hitting ESC disabled filters, but checkbox stays enabled:
<img width="256" alt="image" src="https://user-images.githubusercontent.com/15780643/173005672-95fc52bf-eac1-4bd7-8953-3e125a7d613a.png">

**Comment by RobertStrulak** [comment]
@skalkin @alex-aprm - please take a look at @katerina-stepanova comment ^^

**Comment by RobertStrulak** [comment]
@skalkin @aparamonov-datagrok @katerina-stepanova 
This morning we had another round on the expected behavior of the "ESC" button. We decided following:

- If there are some rows / columns selected in the table hitting of "ESC" button clears the selection (no impact on filters)
- If no rows / columns are selected hitting of the "ESC" button results in disabling / enabling filters (changing the state  of "Turn filters on/off" checkbox)

**Apart from the above please look into the checkbox "Turn filters on/off" itself. Currently it doesn't not work at all (grok version 1.3.5)**

**Comment by katerina-stepanova** [comment]
@skalkin @aparamonov-datagrok 
Summary on current behaviour (DG 1.4.1):
1. Turn filters on/off checkbox is not working: clicking it does not enable/disable all filters
2. Clicking ESC with focus on table does not affect selected columns. This also happens on Ctrl-Shift-A or Select > None.
Because of this, if focus is on table and there are columns selected, filters on/off is never triggered: selected columns are detected > clear selection action is fired > columns are still selected > another attempt to clear selection happens with next ESC
3. Clicking ESC with focus on filters panel is toggling filters on/off and does not affect selection
